### ISSUE TITLE
TASK: [create-fr-user | copy bin helpers] failing

### ISSUE THREAD

**Issue by nirving** [wstrange/frstack#8]
Fresh install when using vagrant. Nothing in staging directory.
```
TASK: [create-fr-user | copy bin helpers] *************************************
failed: [oisserver] => (item=list-policies) => {"failed": true, "item": "list-policies"}
msg: failed to checksum remote file. Checksum error code: 3
failed: [oisserver] => (item=import-policies) => {"failed": true, "item": "import-policies"}
msg: failed to checksum remote file. Checksum error code: 3

FATAL: all hosts have already failed -- aborting
```

Any ideas on what I have done wrong?

Regards
Nicholas Irving

**Comment by nirving** [comment]
Fixed it by doing the following in 
```/ansible/roles/create-fr-user/tasks/main.yml````

```
- name: copy bin helpers
  template: src={{item}} dest={{home_dir}}/bin mode=0755 owner=fr
  with_items:
   - list-policies
   - import-policies
```
to
```
- name: copy bin helpers
  template: src={{item}} dest={{home_dir}}/bin/{{item}} mode=0755 owner=fr
  with_items:
   - list-policies
   - import-policies
```

**Comment by wstrange** [comment]
Thanks for the fix!

**Comment by jperezsorrosal** [comment]
I had the same problem with ansible in different project. 
`msg: failed to checksum remote file. Checksum error code: 3`


The `dest` parameter was a directory as in your first solution. It was enough to use slash at the end so it know it is a directory.
So you could have use `dest={{home_dir}}/bin/` instead of `dest={{home_dir}}/bin`.
